### PR TITLE
Implement font size editing for overlayed text

### PR DESCRIPTION
**Pull request by lgaleana-llm**
This PR implements the feature to allow users to edit the font size of the overlayed text on images. The changes include:

1. **Frontend Changes:**
    - Added a font size input field in the UI for each image container.
    - Updated JavaScript to capture the selected font size and include it in the data sent to the backend when downloading the image.
    - Modified the drag-and-drop functionality to account for changes in font size.

2. **Backend Changes:**
    - Updated the `/download-image` endpoint to accept the font size parameter.
    - Modified the image processing logic to use the specified font size when overlaying the text.

3. **Testing:**
    - Updated existing unit tests to include font size.
    - Added new unit tests to verify the font size functionality.
    - Updated existing Playwright tests to include font size.
    - Added new Playwright tests to verify the font size functionality.

### Test Plan

pytest / playwright

### CODE REVIEW

**Comment by lgaleana-llm** [comment]
!!!!! WARNING: Unrelated tests aren't passing !!!!!

**Comment by lgaleana-llm** [comment]
Total time to create PR: 129.92 seconds
Total OPenAI cost: 0.790725

**Comment by lgaleana** [comment]
The text does increase in size when I download the image. However, when I'm changing the font size on the ui, I don't see the size being updated in real time.

**Comment by lgaleana-llm** [comment]
Thank you for the feedback! I'll update the PR to ensure that the font size changes are reflected in real-time on the UI. I'll add an event listener to update the font size dynamically as the user adjusts the input. I'll make the necessary changes and push an update shortly.

**Comment by lgaleana-llm** [comment]
Total time to amend PR: 77.50 seconds
Total OPenAI cost: 0.491005

**Pull request closed without merging**
