### PR TITLE
Fix CORS issues for image cropping by proxying image requests through backend

### PR DESCRIPTION
**Pull request by lgaleana-llm**
This PR addresses the CORS issues encountered when attempting to crop images by implementing a backend proxy for image requests. The changes include:

1. **Backend Endpoint**: Added a new endpoint in `app/routes.py` to fetch and serve images from external URLs, bypassing CORS restrictions.
2. **Frontend Update**: Modified `templates/static/scripts.js` to request images from the new backend endpoint instead of directly from the external URL.
3. **Testing**: Added a new test file `tests/test_fetch_image.py` to ensure the new backend endpoint correctly fetches and serves images.

### Test Plan

pytest / playwright

### CODE REVIEW

**Comment by lgaleana-llm** [comment]
!!!!! WARNING: Unrelated tests aren't passing !!!!!

**Comment by lgaleana-llm** [comment]
Total time to create PR: 98.11 seconds
Total OPenAI cost: 0.4948

**Comment by lgaleana** [comment]
Why is a proxy the right way to do this?

**Review by lgaleana — APPROVED** [review]

**Comment by lgaleana-llm** [comment]
Using a proxy is a common approach to handle CORS issues because it allows the server to fetch the resource on behalf of the client, thus avoiding the CORS restrictions imposed by the browser. This way, the server can include the necessary CORS headers in its response, ensuring that the client can access the resource without encountering CORS errors. This method is particularly useful when dealing with third-party resources that do not include the required CORS headers.

**Comment by lgaleana-llm** [comment]
Total time to amend PR: 12.49 seconds
Total OPenAI cost: 0.099955

**Comment by lgaleana-llm** [comment]
The issue seems to be with the assertion of the image URLs. Since we are now using a proxy endpoint (`/fetch-image`) to fetch the images, the expected URLs in the tests should be updated accordingly. I'll update the tests to reflect this change.

**Comment by lgaleana-llm** [comment]
Total time to amend PR: 138.05 seconds
Total OPenAI cost: 0.75736

**Pull request merged**
