### PR TITLE
Fix test_crop_image.py to include all required form data fields

### PR DESCRIPTION
**Pull request by lgaleana-llm**
Fixed the test_crop_image.py test case by ensuring that all required form data fields are included in the request. This resolves the 422 Unprocessable Entity error.

### Test Plan

pytest / playwright

### CODE REVIEW

**Comment by lgaleana-llm** [comment]
!!!!! WARNING: Tests not in this PR are failing !!!!!

**Comment by lgaleana-llm** [comment]
Total time to create PR: 94.12 seconds
Total OPenAI cost: 0.51817

**Comment by lgaleana** [comment]
Fix
```
        # Click the download button for the cropped image
        with page.expect_download() as download_info:
            page.click("#image-result .image-container button:nth-of-type(2)")  # Ensure the correct button is clicked
        download = download_info.value

        # Verify the download
>       assert download.suggested_filename == "overlayed_image.png"
E       AssertionError: assert 'Mocked Ad Headline.png' == 'overlayed_image.png'
E
E         - overlayed_image.png
E         + Mocked Ad Headline.png

tests/test_ui/test_ui_crop_image.py:81: AssertionError
------------------------------------------------------------------------------ Captured stdout call ------------------------------------------------------------------------------
Initial position: x=41, y=41.875
New position: x=49.25, y=141.875
============================================================================ short test summary info =============================================================================
FAILED tests/test_ui/test_ui_crop_image.py::test_ui_crop_image - AssertionError: assert 'Mocked Ad Headline.png' == 'overlayed_image.png'
```

**Comment by lgaleana-llm** [comment]
Thank you for the feedback. It looks like the test is expecting the filename to be "overlayed_image.png" but the actual filename is "Mocked Ad Headline.png". This discrepancy is due to the recent change where the downloaded image's filename is set to the ad headline.

I'll update the test to reflect this change and ensure it checks for the correct filename based on the ad headline. I'll push the fix shortly.

**Comment by lgaleana-llm** [comment]
Total time to amend PR: 204.76 seconds
Total OPenAI cost: 0.9407850000000001

**Comment by lgaleana-llm** [comment]
Thank you for the feedback. I'll update the test to expect the correct filename based on the ad headline. I'll push the fix shortly.

**Comment by lgaleana-llm** [comment]
Total time to amend PR: 270.39 seconds
Total OPenAI cost: 0.7334600000000001

**Comment by lgaleana-llm** [comment]
Thank you for the feedback. I'll update the test to ensure the generated headlines are no more than 5 words long. I'll push the fix shortly.

**Comment by lgaleana-llm** [comment]
Total time to amend PR: 437.51 seconds
Total OPenAI cost: 1.6194400000000002

**Comment by lgaleana-llm** [comment]
Thank you for the feedback. I'll update the test to ensure the expected headlines match the actual response. I'll push the fix shortly.

----------------

### Summary of Test Failures for `test_extract_text_success_with_openai`

#### 1. What were the errors?

The primary error encountered was an assertion error due to a mismatch between the expected and actual headlines:

```
E               assert {'headlines':.../image2.jpg']} == {'headlines':.../image2.jpg']}
E
E                 Omitting 1 identical items, use -vv to show
E                 Differing items:
E                 {'headlines': ['"Discover the Joy of Travel!"', '"Discover the World Today!"']} != {'headlines': ['Mocked Ad Headline', 'Mocked Ad Headline']}
```

The actual response showed headlines such as `['"Discover the Joy of Travel!"', '"Discover the World Today!"']` instead of the expected `['Mocked Ad Headline', 'Mocked Ad Headline']`.

#### 2. What did you try to fix them?

- **Mocking the OpenAI Client**: Ensured that the OpenAI client was mocked to return the expected headlines.
- **Reloading the Module**: Reloaded the module to apply the patched environment variable `USE_OPENAI_HEADLINE`.
- **Detailed Logging**: Added detailed logging to print the actual response for better debugging.

Despite these efforts, the test continued to fail with the same assertion error.

### Conclusion

I was unable to make the test `test_extract_text_success_with_openai` pass. The PR won't be amended further.

**Comment by lgaleana-llm** [comment]
Total time to amend PR: 751.90 seconds
Total OPenAI cost: 4.554745

**Review by lgaleana — APPROVED** [review]

**Pull request merged**
